"""empty message

Revision ID: c04239b75198
Revises: 
Create Date: 2024-07-12 08:30:21.263817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04239b75198'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['t_title.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['t_title.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_publish_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['t_title.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('publish_time_id', sa.Integer(), nullable=True),
    sa.Column('description_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['description_id'], ['t_description.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['t_photo.id'], ),
    sa.ForeignKeyConstraint(['publish_time_id'], ['t_publish_time.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['t_title.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('publish_time_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['t_photo.id'], ),
    sa.ForeignKeyConstraint(['publish_time_id'], ['t_publish_time.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['t_title.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_post')
    op.drop_table('t_article')
    op.drop_table('t_publish_time')
    op.drop_table('t_photo')
    op.drop_table('t_description')
    op.drop_table('t_title')
    # ### end Alembic commands ###
